### ISSUE TITLE
Not compiling anymore

### ISSUE THREAD

**Issue by sachaz** [antifork/hopfake#1]
Hi,

I used your nice code long time ago and wanted to recompile it:

1. Need to install pcab
On Debian `apt-get install libpcap-dev`
2. fatal error: net/bpf.h
ln -s /usr/include/pcap-bpf.h /usr/include/net/bpf.h
3. Compiling error:
~~~
hopfake.c: In function ‘get_interface_addr’:
hopfake.c:698:11: error: expected expression before ‘+=’ token
  (char *) += ifr
           ^~
~~~

**Comment by vjt** [comment]
Hi - it should work now. Enjoy :-)

**Comment by sachaz** [comment]
Hey gracie 1000 Marcello, happy to see you still there :)
